apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch-app-ingress-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hoppscotch.greenie.one
      secretName: greenie-hoppscotch-dev-tls-prod
  rules:
    - host: hoppscotch.greenie.one
      http:
        paths:
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: hoppscotch-app
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch-backend-ingress-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hoppscotch.greenie.one
      secretName: greenie-hoppscotch-dev-tls-prod
  rules:
    - host: hoppscotch.greenie.one
      http:
        paths:
          - pathType: Prefix
            path: /backend(/|$)(.*)
            backend:
              service:
                name: hoppscotch-backend
                port:
                  number: 3000
