apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remote-ingress-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev-api.greenie.one
      secretName: greenie-remote-dev-tls-prod
  rules:
    - host: dev-api.greenie.one
      http:
        paths:
          - path: /remote(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: greenie-remote-dev
                port:
                  number: 8080
