ingester:
  replicas: 1
  config:
    replication_factor: 1
  persistence:
    enabled: true
    size: 1Gi
    type: pvc
    storageClass: azurefile
    accessModes:
    - ReadWriteOnce

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true