prometheusOperator:
  prometheusConfigReloader:
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
grafana:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: azurefile
    accessModes:
    - ReadWriteOnce
    size: 1Gi
    finalizers:
    - kubernetes.io/pvc-protection
alertmanager:
  enabled: false
