apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-prod

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - greenie.one
      secretName: greenie-frontend-tls-prod
  rules:
    - host: greenie.one
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: greenie-mvp-entrypoint
                port:
                  number: 3000
