apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - redis.greenie.one
      secretName: redis-dev-tls-prod
  rules:
    - host: redis.greenie.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis-dev-master
                port:
                  number: 6379
