apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://greneie.one, https://dev.greenie.one"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, DELETE, PATCH, OPTIONS

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.greenie.one
      secretName: greenie-auth-tls-prod
  rules:
    - host: api.greenie.one
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: greenie-auth-prod
                port:
                  number: 8080
