apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://greneie.one, https://prod.greenie.one, http://localhost:3000"
    nginx.ingress.kubernetes.io/auth-url: http://greenie-auth-prod.auth.svc.cluster.local:8080/validate_token
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_x_user_details;    
      proxy_set_header x-user-details $token;

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.greenie.one
      secretName: greenie-utils-prod-tls-prod
  rules:
    - host: api.greenie.one
      http:
        paths:
          - path: /utils(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: greenie-utils-prod
                port:
                  number: 3030
