name: Deployment

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create KUBECONFIG
        run: |
          echo $KUBECONFIG_B64 | base64 --decode > greenie-kubeconfig.yaml
          echo "KUBECONFIG=$(realpath greenie-kubeconfig.yaml)" >> $GITHUB_ENV

      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Mongo DB"
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami 
          helm install --namespace mongodb mongodb-dev bitnami/mongodb
