name: Deployment

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create KUBECONFIG
        run: |
          echo $KUBECONFIG_B64 | base64 --decode > greenie-kubeconfig.yaml
          echo "KUBECONFIG=$(realpath greenie-kubeconfig.yaml)" >> $GITHUB_ENV

      - name: "Mongo DB"
        uses: "deliverybot/helm@v1"
        with:
          release: "mongodb-dev"
          namespace: "mongo"
          chart: "app"
          token: "${{ github.token }}"
          repo: "https://charts.bitnami.com/bitnami"
          repo-alias: bitnami
