name: Deployment

on:
  push:
    branches:
      - main

env:
  KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create KUBECONFIG
        run: |
          echo $KUBECONFIG_B64 | base64 --decode > greenie-kubeconfig.yaml
          echo "KUBECONFIG=$(realpath greenie-kubeconfig.yaml)" >> $GITHUB_ENV

      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Mongo DB"
        run: |
          kubectl create namespace mongodb --dry-run=client -o yaml | kubectl apply -f -
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install --namespace mongodb mongodb-dev bitnami/mongodb

      - name: "Nginx ingress controller"
        run: |
          kubectl create namespace nginx-ingress --dry-run=client -o yaml | kubectl apply -f -
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install --namespace nginx-ingress nginx-ingress ingress-nginx/ingress-nginx --set controller.publishService.enabled=true

      - name: "Apply Ingress"
        run: |
          kubectl apply -f ingress/backend.yaml
